import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
      </div>

      <div>
        {/* <Image height={500} width={1000} style={{width:'100% !important' }} src="/banner.webp" /> */}
     <img className=" sm:w-full  md:w-full mb-2" src="https://natalieminhinteractive.com/wp-content/uploads/2020/03/ecommerce-website-banner.png" alt="" />
      </div>

    </>
  );
}
